---
version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/mpol/overseerr/config:/config
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entrypoints=http"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.local.mrpol.eu`)"
      - "traefik.http.middlewares.overseerr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.overseerr.middlewares=overseerr-https-redirect"
      - "traefik.http.routers.overseerr.entrypoints=https"
      - "traefik.http.routers.overseerr-secure.rule=Host(`overseerr.local.mrpol.eu`)"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.overseerr-secure.tls=true"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true